<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCuNUb0x\appApp_AppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCuNUb0x/appApp_AppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCuNUb0x.legacy');

    return;
}

if (!\class_exists(appApp_AppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCuNUb0x\appApp_AppKernelDevDebugContainer::class, appApp_AppKernelDevDebugContainer::class, false);
}

return new \ContainerCuNUb0x\appApp_AppKernelDevDebugContainer([
    'container.build_hash' => 'CuNUb0x',
    'container.build_id' => '0dbfa9c6',
    'container.build_time' => 1640108723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCuNUb0x');
